name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: echo "Running thing" && clang++ hell.cpp -o hell.out && sudo ./hell.out && "Echo done running thing"
