name: Build And Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Test
      run: chmod +x  .github/scripts/build_and_test.sh && ./.github/scripts/build_and_test.sh
    # - name: make
    #   run: make
    # - name: make check
    # run: make check
    # - name: make distcheck
    #  run: make distcheck
